language: node_js
node_js:
 - 10.16

sudo: false

cache:
  directories:
  - node_modules

services:
  - postgresql

before_install:
  - npm install -g npm@latest
  - npm i -g @adonisjs/cli

install: 
  - npm ci

before_script:
  - psql -c 'CREATE DATABASE actividades;' -U postgres 

script: 
  - adonis migration:run
  - adonis test

provider: heroku
api_key:
  secure: 837313c7-27b5-4015-9ffc-0ecd9212297e